### ISSUE TITLE
Cannot build using `make esp32` - missing `sdkconfig.h`

### ISSUE THREAD

**Issue by kasperl** [toitlang/toit#205]
```
.../toit/third_party/esp-idf/components/newlib/platform_include/assert.h:20:10: fatal error: sdkconfig.h: No such file or directory
 #include <sdkconfig.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
make: *** [build/esp32/lib/libtoit_image.a] Error 1
```

**Comment by kasperl** [comment]
Problem seems to have been introduced in e26f1e217039dbfbcb42bfa75e476035f2911050. Can you take a look, @dsobotta?

It is probably just a missing dependency. I was hit by this after cleaning out my `build/` directory.
